cli-bss.py - Argument --offset
dsi-univ-rennes1/libPythonBssApi pull request #5
Opened 2018-06-15 15:39 UTC by emmanuel-benoit

Ajouté l'argument --offset pour les listes de comptes ou de CoS.

2018-06-19 15:48 UTC, salaun-urennes1 requested changes
Def de action_args à corriger

2018-06-19 15:48 UTC, salaun-urennes1 commented on cli-bss.py
> +    action_args = {
Une typo dans le code proposée : les clés du dictionaire action_args doivent être entre quotes. Sinon : 
```
Traceback (most recent call last):
  File "./cli-bss.py", line 361, in <module>
    domain: args[ 'domain' ] ,
NameError: name 'domain' is not defined
```

2018-06-20 07:15 UTC, emmanuel-benoit commented on cli-bss.py
> +    action_args = {
Corrigé.

2018-06-20 07:24 UTC, salaun-urennes1 commented on cli-bss.py
> +    action_args = {
Bonjour Emmanuel,
Merci pour le correctif ; le code s'exécute maintenant.
Par contre il semble que l'API BSS ne supporte pas les paramètres limit et offset pour la fonction GetAllCos, cf https://dashboard.partage.renater.fr/api_bss_documentation.html#_6_1_getallcos.

J'ai effectué un test qui semble confirmer qu'il ignore ces paramètres :
`./cli-bss.py --domain=univ-rennes1.fr --domainKey=XXX --getAllCos --limit=1 --offset=1` me retourne 4 résultats, en partant du 1er.

2018-06-20 07:50 UTC, emmanuel-benoit commented on cli-bss.py
> +    action_args = {
Bonjour Olivier.
OK. Le code d'origine avait le paramètre `limit`, j'ai donc rajouté l'offset sans vérifier (nous n'avons que 3 CoS...).
Veux-tu que je supprime carrément l'utilisation de ces paramètres pour `GetAllCos`?

2018-06-20 10:37 UTC, salaun-urennes1 commented on cli-bss.py
> +    action_args = {
Oui, s'il te plait.

2018-06-20 12:09 UTC, emmanuel-benoit commented on cli-bss.py
> +    action_args = {
OK. J'ai aussi supprimé le paramètre ldap_query qui n'était pas pris en compte non plus.

2018-06-21 14:34 UTC, merged